### ISSUE TITLE
3D Tiles 1.1 CesiumJS roadmap

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10089]
The next couple weeks, we've been revising the 3D Tiles Next extensions to prepare for standardizing as 3D Tiles 1.1. The CesiumJS implementation needs to be updated in the following areas:

- Metadata: `EXT_mesh_features` is now split into `EXT_mesh_features` (for feature IDs) and `EXT_structural_metadata` (for metadata)
- Implicit Tiling: the extensions are now folded into the subtree JSON and a few other changes.

There's quite a few changes, so this list will help our PRs organized. This checklist is in roughly the order that things should be merged:

- [x] @j9liu https://github.com/CesiumGS/cesium/pull/10083
- [x] @ptrgags to avoid complications later, merge `metadata-spec-changes-staging` and `implicit-tiling-changes-staging` into a single staging branch (`extension-revisions`). grab the latest `main` while we're at it
- [x] @j9liu https://github.com/CesiumGS/cesium/issues/10084
- [x] @ptrgags finish https://github.com/CesiumGS/cesium/pull/10087
- [x] @j9liu https://github.com/CesiumGS/cesium/issues/10088
- [x] @j9liu https://github.com/CesiumGS/cesium/issues/10103
- [x] @ptrgags handle changes to metadata types #10116 
- [x] @j9liu https://github.com/CesiumGS/cesium/issues/10104
- [x] @ptrgags #10119 
- [x] @ptrgags https://github.com/CesiumGS/cesium/pull/10122
- [x] @ptrgags https://github.com/CesiumGS/cesium/pull/10135 
- [x] @j9liu https://github.com/CesiumGS/cesium/issues/10105
- [x] https://github.com/CesiumGS/cesium/issues/10095
- [ ] @ptrgags offset/scale for property tables
- [x] changes from 3D Tiles 1.1 schema once available 

For reference, here are links to the latest schemas (specs still pending):

- (updated) [3DTILES_implicit_tiling subtree schema](https://github.com/CesiumGS/3d-tiles/tree/extension-revisions-implicit/extensions/3DTILES_implicit_tiling/schema/subtree)
- (updated) [EXT_mesh_features schema](https://github.com/CesiumGS/glTF/tree/ext-mesh-features-revision/extensions/2.0/Vendor/EXT_mesh_features/schema)
- (new) [EXT_structural_metadata schema](https://github.com/CesiumGS/glTF/tree/ext-mesh-features-revision/extensions/2.0/Vendor/EXT_structural_metadata/schema)
