### ISSUE TITLE
Cesium Inspector Roadmap

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1025]
Create a new widget that will ultimately replace the Terrain Inspector app.  Do not use Dojo.

**Phase One**
- [x] Click on primitive to show bounding sphere(s) (`debugShowBoundingVolume`)
- [x] Click on primitive to show `modelMatrix` reference frame (`DebugModelMatrixPrimitive`)
- [x] Click on primitive to draw only it (`Scene. debugCommandFilter`)
- [x] Option to show FPS (`PerformanceDisplay`).  Make sure the size isn't too small.
- [x] Option to color-code commands based on the frustum (`Scene.debugShowFrustums`)
- [x] Option to show number of commands executed in one, two, or more frustums (`Scene. debugFrustumStatistics`)
- [x] Terrain Inspector features

**Phase Two**
- [ ] Adjust frustums, e.g., switch from one to multiple frustums
- [ ] Ability to disable `DrawCommand` culling, e.g., as if all commands had `boundingVolume === undefined`.
- [ ] Display if translucency is `OIT MRT`, `OIT Multipass`, or `Alpha blending`.
- [ ] Display drawing buffer width and height.
- [ ] Option to color-code individual commands (`Scene.debugShowCommands`)
- [ ] HUD with terrain stats
- [x] Improve `PerformanceDisplay`.  #1350 
- [x] ~~Ability to change resolution scale (good for testing fill rate)~~. #1678, Browsers debuggers support this now.

~~**Phase Three**~~
- [x] ~~Model debugging.  Show stats.  Show wireframe (`Model.debugShowWireframe`).  See @pjcozzi~~
- [x] ~~Click on a model, show and play its animations and other metadata.~~

**Phase Four**
- [ ] Show what WebGL extensions are in use.
- [ ] Option to freeze the frame, but still move the camera around to investigate culling, etc.
- [ ] Option to visualize vertex attributes similar to (or instead of) [`createTangentSpaceDebugPrimitive`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/createTangentSpaceDebugPrimitive.js).
- [ ] Option to turn primitives to wireframe (not sure how yet).
- [x] ~~Option to show all shaders in the shader cache and allow us to edit them (as opposed to editing the orginial .glsl files)~~.  Firefox now has a [tool](https://hacks.mozilla.org/2013/11/live-editing-webgl-shaders-with-firefox-developer-tools/) for this.

**TBA**
- [ ] Write a short tutorial on how to integrate the widget and use the app
- [ ] Consider a hot key or Chrome Extension to make this painless to bring up.

**Comment by ggetz** [comment]
This is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
