### ISSUE TITLE
`ModelExperimental` -> `Model` Roadmap

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10346]
One of the major items on the 3D Tiles Next Roadmap (#9520) is bringing `ModelExperimental` up to feature parity with `Model`, so that it can entirely replace it. In other words, we aim to remove the current `Model` class and any related files, and rename `ModelExperimental` to `Model` without any hiccups.

This issue goes into more detail than the overall roadmap and will be updated as necessary.

**Remaining `ModelExperimental` Features**
- [x] Basic 2D / CV rendering: #9934
- [x] Clamp to ground #10448 
- [x] Support `AGI_articulations` #10479 
- [x] Support silhouettes #10457 
- [x] Support `distanceDisplayCondition` #10481 
- [x] Add `options.id` for picking #10491 
- [x] Add `options.credit` #10489 
- [x] Add `options.asynchronous` #10490 
- [x] Rendering statistics #9886
- [x] Support outline extension for OSM buildings: #10338
- [x] Integration with entities and CZML systems: #10285
- [ ] Use `GltfLoader` in `ClassificationModel`

**Important bugfixes**
- [ ] Normal mapping rendering bug: #10296
- [x] Custom shaders and instancing bug: #10113
- [ ] 3D Tiles BIM model crashes: [comment](https://github.com/CesiumGS/cesium/issues/10379#issuecomment-1127913756) in #10379 
- [x] OSM buildings render differently #10338 

**Lower-priority bugfixes**
- [ ] Quantized animation bug: #10321 
- [ ] Morph targets unit test failure:  #10354 
- [ ] Artifacts in 2D / CV when rendering over IDL: #10401 (fix in the distant future)
- [ ] Some tilesets not showing up with `projectTo2D` in 2D / CV #10402 (more related to bounding volumes in 2D than `ModelExperimental` itself)

**Testing**
- [x] Ensure all models from [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0) load correctly with `ModelExperimental`
- [ ] Ensure that tilesets load correctly with `ExperimentalFeatures.enableModelExperimental` set to true
- [x] Ensure that entities and CZML work with `ModelExperimental`
- [ ] Go through the "category - gltf" label for any important lingering issues
- [ ] Go through Sandcastles and make sure they work with ModelExperimental. See https://github.com/CesiumGS/cesium/issues/10379

**Files to remove**
- [ ] `Model`
- [ ] `ModelInstanceCollection`
- [ ] `ModelAnimationCache`
- [ ] `ModelAnimation`
- [ ] `ModelAnimationCollection`
- [ ] `ModelNode`
- [ ] `ModelMesh`
- [ ] `ModelUtility` -- make sure it no longer needs to be used by `ClassificationModel`
- [ ] `ModelOutlineLoader`
- [ ] all related specs

**Files to rename**
- [ ] `ModelExperimental` and related architecture
  - [x] `ModelExperimentalSceneGraph`
  - [ ] `ModelExperimentalNode`
  - [x] `ModelExperimentalPrimitive`
  - [x] `ModelExperimentalSkin`
  - [x] `ModelExperimentalAnimationChannel`
  - [ ] `ModelExperimentalAnimation`
  - [ ] `ModelExperimentalAnimationCollection`
  - [x] `ModelExperimental3DTileContent`
  - [x] `ModelExperimentalType`
  - [ ] `ModelExperimentalUtility`
- [ ] Shaders
  - [ ] `ModelExperimentalVS`
  - [ ] `ModelExperimentalFS`
- [ ] `loadAndZoomToModelExperimental`
- [ ] all related specs

**Comment by lilleyse** [comment]
This is very exciting! Just a few more things to add from me:

* **glTF 1.0**: Is the custom shader architecture flexible enough that it could allow glTF 1.0 models to still work? The main model we're concerned about is https://sandcastle.cesium.com/?src=3D%20Tiles%20BIM.html. It may not be easy to find a replacement. We need to put in a day or two to come up with a plan here.
* If we decide to deprecate anything, it should be mentioned in the June release
* Documentation sweep to make sure that everything marked `@private` should remain `@private`
* We should consider setting `tileset.enableModelExperimental = true` by default so that we can start catching regressions early. We should test as many 3D Tiles datasets as we can find and allow for a couple weeks for bug fixes.
* Re `ModelUtility` - it would be annoying to maintain two utility files. It might be worth updating `ClassificationModel` to use `GltfLoader` even though it's lower on the priority list.

**Comment by j9liu** [comment]
Should we consider adding a `url` option to the `ModelExperimental.fromGltf` constructor? `Model.fromGltf` takes a `url` whereas `ModelExperimental.fromGltf` takes `gltf`, so this will break things when we make the switch from `Model` to `ModelExperimental`.

**Comment by lilleyse** [comment]
@j9liu yeah definitely. I got tripped up by this earlier today. Could you open a PR for that?

**Comment by j9liu** [comment]
Going through the glTF 2.0 sample models, leaving notes where I see differences:

**Attenuation Test**

The cubes are colored blue in glTF-Sample-Viewer, but not for `ModelExperimental`.

| glTF-Sample-Viewer | `ModelExperimental` | 
| ---------------------- | ----------------------- |
| ![image](https://user-images.githubusercontent.com/32226860/176755735-14839e79-0860-4c8e-a747-9ecad94a0e0d.png) | ![image](https://user-images.githubusercontent.com/32226860/176755951-5c10c9f2-b35f-4efa-bd44-4be96f620ff7.png)|

`Model` renders this the same as `ModelExperimental`
