### ISSUE TITLE
Camera Roadmap

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1060]
- [x] Higher-level interfaces, e.g., like #977, #2007.  Details TBA.
- [ ] Collision prediction and avoidance: prevent undesirable effects like passing through the globe or models. See Chapter 9 in [Real-Time Cameras](http://www.amazon.com/Real-Time-Cameras-Mark-Haigh-Hutchinson/dp/0123116341).  We should be able to make volumes, e.g., a rectangle around a model, that the user can't enter. #1977 ~~#449~~
- [x] Better interaction with terrain. #549
- [x] Better interaction with terrain when following an object on terrain. #1936
- [x] Better ability to lookup from the ground.
- [ ] Easier zoom to a location. #2816, ~~#302~~
- [x] Improve flights. #1158, #802, #804, #1400, #2093, #2468
- [ ] More flights. #1401, #2027
- [ ] Improve 3D/2D/Columbus view transitions. #451, #1596, #2065
- [ ] Consistent mouse controls. #453, #1200 
- [ ] API to set home view. #1798 
- [x] Improved Touch. #1978 
- [x] Movement events. #2366
- [x] VR support
   - https://github.com/AnalyticalGraphicsInc/cesium/pull/4778
  - http://casual-effects.blogspot.com/2015/01/adapting-camera-entity-for-virtual.html
  - https://twitter.com/morgan3d/status/608710628958720000
- [ ] Reevaluate `ScreenSpaceCameraController` options. Some may be better suited on the `Camera`. https://github.com/AnalyticalGraphicsInc/cesium/pull/4105#discussion_r73053082

**Experimental ideas**
- [ ] Follow two objects, e.g., two aircrafts, using the rule of thirds. There is a chapter in [Jim Blinn's Corner: A Trip Down the Graphics Pipeline](http://www.amazon.com/Jim-Blinns-Corner-Graphics-Pipeline/dp/1558603875).
- [ ] Stabilize camera.  For example, if we are following a ground vehicle through the mountains, don't use a fixed position in the vehicle's body frame.  Instead just keep a bounding sphere in view.  Could be a special case of above.
- [ ] Focus the view on one object while keeping another object in view, e.g., a satellite and Earth, or a satellite and a ground station it has access it.  Again, probably a special case of above if there is a generic system.
- [ ] Physics: camera shake when rocket takes off.
