### ISSUE TITLE
Ongoing documentation fixes

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#11749]
There occasionally are "small" fixes for the generated docmentation. These range from "fixing typos" to "fixing broken links" or "fixing type annotations". These usually do not involve rigorous tests, because this _only_ refers to fixes that do _not_ affect the functionality. A corner case is that of TSDoc fixes that may affect the generated typings. These may warrant some scrutiny, but still are not covered by real specs, but maybe only by a few lines in the [`Specs/TypeScript/index.ts` file](https://github.com/CesiumGS/cesium/blob/6e8b5d8fba959dd4df92c1aa4c69c6a62900aa0d/Specs/TypeScript/index.ts).

I'd suggest listing these issues here. Everybody can add comments with things that have to be fixed, and we can try to keep track of the things that have been addressed using GitHub `[ ] Task checkboxes`.

- [x] The `Cesium3DTileset.from...` functions claim to throw a `DeveloperError` when the tileset version is not `0.0` or `1.0`. (E.g. [`fromUrl`](https://github.com/CesiumGS/cesium/blob/6e8b5d8fba959dd4df92c1aa4c69c6a62900aa0d/packages/engine/Source/Scene/Cesium3DTileset.js#L1933) and `fromIonAssetId`). 
  **Suggested fix:** This should include `1.1` as a valid version number. 
- [x] These functions are actually not throwing a `DeveloperError`, but a `RuntimeError`, as of [this check](https://github.com/CesiumGS/cesium/blob/6e8b5d8fba959dd4df92c1aa4c69c6a62900aa0d/packages/engine/Source/Scene/Cesium3DTileset.js#L2122). 
  **Suggested fix:** Considering that the developer does not have influence on whether ~"the data is valid", it should probably be a `RuntimeError` (and documented accordingly)
- [x] The `...GeometryUpdater#isDynamic` property documentation contains invalid links. (For example, the [`PolylineGeometryUpdater` documentation](https://cesium.com/learn/cesiumjs/ref-doc/PolylineGeometryUpdater.html#isDynamic), generated from [`PolylineGeometryUpdater`](https://github.com/CesiumGS/cesium/blob/9f43e81832fd90a4d3e6b67f6b168b6131bf7ce6/packages/engine/Source/DataSources/PolylineGeometryUpdater.js#L259), but also other updater classes). 
  **Suggested fix:** It should just omit the part that says
  ```
   * If true, all visualization is delegated to the {@link DynamicGeometryUpdater}
   * returned by GeometryUpdater#createDynamicUpdater.
  ```
  This is an implementation detail that is not relevant for the reader of the documentation.
- [x] The [`EntityCollection#add` function](https://github.com/CesiumGS/cesium/blob/9f43e81832fd90a4d3e6b67f6b168b6131bf7ce6/packages/engine/Source/DataSources/EntityCollection.js#L268) claims to throw a `DeveloperError` for duplicate IDs, but actually throws a `RuntimeError`.
  **Suggested fix:** It should be a `DeveloperError`. The developer should make sure that there are no duplicate IDs. (In doubt, the developer can trivially check whether an ID is already present)

- [x] The `orientation` property in the [entity constructor options](https://github.com/CesiumGS/cesium/blob/7ea4b84b681cd17bc61a64921837d4380040ae24/packages/engine/Source/DataSources/Entity.js#L74) is documented to be of type `Property`, but it can also be a `Quaternion`.
  **Suggested fix:** Change the type to `{Property | Quaternion}`. Investigate whether the same applies to other properties there.

**Comment by javagl** [comment]
- [ ] There are many places that define a specific type for a certain property (like `Cartesian3`), but they also define a `default` value that may be `undefined`. This is an inconsistency insofar that it's not possible to assign `undefined` there, and the type of the property should have been `Cartesian3 | undefined` to begin with. One example (and a regex for finding others) is mentioned in the issue around https://github.com/CesiumGS/cesium/issues/11475#issuecomment-1858825468 
  **Suggested fix:** Add `... | undefined` in all these places
  - Some instances of this have been addressed as part of https://github.com/CesiumGS/cesium/pull/12193 
  - Further instances of this have been addressed in https://github.com/CesiumGS/cesium/pull/12736 

- [ ] It's not really a "documentation" fix, but ... way not warrant a full-fledged PR: I _think_ that [this `updateStages`](https://github.com/CesiumGS/cesium/blob/ba6f5a31ba210527a7e11274285a50aa3001d8ac/packages/engine/Source/Scene/Model/ModelRuntimePrimitive.js#L175) is not used
  **Suggested fix:** Remove it...

**Comment by Tony3141Hui** [comment]
> * There are many places that define a specific type for a certain property (like `Cartesian3`), but they also define a `default` value that may be `undefined`. This is an inconsistency insofar that it's not possible to assign `undefined` there, and the type of the property should have been `Cartesian3 | undefined` to begin with. One example (and a regex for finding others) is mentioned in the issue around [Can't unset constrainedAxis in typescript without casting  #11475 (comment)](https://github.com/CesiumGS/cesium/issues/11475#issuecomment-1858825468)
>   **Suggested fix:** Add `... | undefined` in all these places

Analysing ./pakages/**

```regex
@default\s+(undefined|null)\s*\n([^/]*\n)*.*@type\s+
```

No results, means no `@type` after `@default` in same annotation block.

```regex
@type\s+.*\n([^/]*\n)*.*@default\s+(undefined|null)\s*\n
```

100+ results, means 100+ targets.

```regex
@type\s+.*(undefined|null).*\n([^/]*\n)*.*@default\s+(undefined|null)\s*\n
```

5 results, means 5 correct, including fixed [#11475](https://github.com/CesiumGS/cesium/issues/11475#issuecomment-1858825468), in 100+ targets.

**Comment by javagl** [comment]
(State of 1.121)

- [x] The `InterpolationAlgorithm` that is linked, for example, from [`SampledProperty.setInterpolationOptions`](https://cesium.com/learn/cesiumjs/ref-doc/SampledProperty.html#setInterpolationOptions) (but also other places) leads to a 404 right now
  - This was brought up in https://community.cesium.com/t/interpolationalgorithm-page-lost/35086
  - EDIT: This was fixed via https://github.com/CesiumGS/cesium/pull/13555
- [x] The same applies to `Packable`
- [ ] The `Packable` interface is listed in the ["See..." list of `Matrix4`](https://cesium.com/learn/cesiumjs/ref-doc/Matrix4.html) and others, and should probably be listed in _all_ implementing classes. But it is **not** listed in `Matrix2` and `Matrix3`
- [ ] I think that `positions` in [this line](https://github.com/CesiumGS/cesium/blob/05380a6d7f7869483f63d6a3bbbd89d68ebd1531/Source/Core/GeometryInstance.js#L7) should be `position`**`ed`**
- [ ] The types of the `extension...` objects [here](https://github.com/CesiumGS/cesium/blob/6c2e520420b95bcb6c8eba0f02c76347cee1dd4b/packages/engine/Source/Scene/GltfStructuralMetadataLoader.js#L23) are not `{string}`, but `{object|undefined}`

**Comment by javagl** [comment]
Not really a "documentation" fix, but ...

- [x] Rename https://github.com/CesiumGS/cesium/blob/6c2e520420b95bcb6c8eba0f02c76347cee1dd4b/Apps/Sandcastle/gallery/Globe%20Materials%20%E2%80%93%20Water%20Mask%20Elevation%20Map.html (and the corresponding JPG) to **not** contain that special "–" character!!! (Ever tried to `git add...` such a file at a Windows console?)

(Edit 2025-11-18: This may have become obsolete with the new sandcastle, https://github.com/CesiumGS/cesium/blob/bcc5ea383e294c698940dbf9df76ac5ba6961a73/packages/sandcastle/gallery/globe-materials-water-mask-elevation-map/sandcastle.yaml#L1 )

**Comment by javagl** [comment]
Also not a "documentation" fix, but maybe part of a cleanup that does not affect functionality:

- [ ] I'm pretty sure that [`frameState.light`](https://github.com/CesiumGS/cesium/blob/e3e98371830a85d653c2f9e1f34f382c84984bce/packages/engine/Source/Scene/FrameState.js#L378) is not used. If it _really_ is not used, it could be removed.

**Comment by javagl** [comment]
- [ ] The example/snippet that is currently shown at https://cesium.com/learn/ion-sdk/ref-doc/Camera.html works for a _new_ camera. But as soon as this camera is _used_, it generates a 
  "DeveloperError: normalized result is not a number"
  This is related to the `position` being (0,0,0). I'd go so far and consider this as a _bug_ in the `Camera` itself, but wanted to keep track of this here. 
  Illustration: https://sandcastle.cesium.com/index.html#c=dZFRS8MwFIX/SuhThZE6fbQbQik4UCdzDpRCydLbLZjelCTtmL/eNBWstsvTvfec8yXccIXGklbACTRZEIQTScCIpqI7PwuzgPs+UWiZQNBZcHWXIfc5zirQzOV6AO17JzuDL2mtjLBC4V92wrR1FcPb0MN6byE08B/zyEgRDsxCOBbenlfb/GN2iT+4oKknyVwqvAh+H+RL3RjrPKVqf0FPzB7pyypf79JNvn3YpOk4gMC67c7p9QTMSzdeCmZBbOxZwjJD4s+9qGqlLWm0DCmNLFS1dGsw0b7hn2ApN6Z7YGeNo2E0LkRLRLGY+D/CJTPGKWUj5av4gixYxpHzj6JSsULgYd2Cluzc2Y7z5WM/pJTGkWunk1YpuWf6H/kb

**Comment by javagl** [comment]
- [ ] Not sure what the "callback" part refers to at https://github.com/CesiumGS/cesium/blob/30559097f7d8836c577c1b6842b3970923316b4e/packages/engine/Source/Scene/GltfPipeline/getComponentReader.js#L135

**Comment by javagl** [comment]
- [ ] Not really a "documentation fix", but ... that `, Property.equals` part should be replaced by a `Property.equals` call, at
  - https://github.com/CesiumGS/cesium/blob/1c892c87bd3f6eae234379bcf13344f5d0db6e59/packages/engine/Source/DataSources/CompositeMaterialProperty.js#L118
  -  https://github.com/CesiumGS/cesium/blob/1c892c87bd3f6eae234379bcf13344f5d0db6e59/packages/engine/Source/DataSources/CompositePositionProperty.js#L144
  -  https://github.com/CesiumGS/cesium/blob/1c892c87bd3f6eae234379bcf13344f5d0db6e59/packages/engine/Source/DataSources/CompositeProperty.js#L138
  - https://github.com/CesiumGS/cesium/blob/1c892c87bd3f6eae234379bcf13344f5d0db6e59/packages/engine/Source/DataSources/TimeIntervalCollectionPositionProperty.js#L144
  - https://github.com/CesiumGS/cesium/blob/1c892c87bd3f6eae234379bcf13344f5d0db6e59/packages/engine/Source/DataSources/TimeIntervalCollectionProperty.js#L126

**Comment by javagl** [comment]
- [x] The one that was brought up in https://github.com/CesiumGS/cesium/issues/12537 seems uncontroversial for me...

This was resolved via https://github.com/CesiumGS/cesium/pull/13570

**Comment by javagl** [comment]
- [ ] I'm pretty sure that the word "less" in ["Enabling this option will allow for less frustums in the multi-frustum"](https://github.com/CesiumGS/cesium/blob/d84c095c8ffaa585bc74ae2151a36e4835caa8ec/packages/engine/Source/Scene/Scene.js#L1552) should be "fewer" ...

**Comment by javagl** [comment]
- [X] The documentation says `3x3` where it should say `4x4` at https://github.com/CesiumGS/cesium/blob/b661763788689a93d16a5704645c82b7cfdc18c0/packages/engine/Source/Scene/Model/UniformType.js#L109 (mentioned in https://community.cesium.com/t/collect-typing-errors-in-api-documentation-and-source-code/40332/2 )

EDIT: Fixed via https://github.com/CesiumGS/cesium/pull/12656

**Comment by javagl** [comment]
The PR fixes only the last comment here. Beyond that, this issue is "ongoing", meaning that it will only be closed when the whole documentation is complete and perfect. (I.e. never 🙂 ).

**Comment by lukemckinstry** [comment]
> The PR fixes only the last comment here. Beyond that, this issue is "ongoing"

Thanks @javagl , my mistake, the PR was linked to the issue

**Comment by javagl** [comment]
- [ ] The `Ellipsoid.cartesianToCartographic` function is said to return `Cartesian`, but can actually return `Cartesian | undefined`: https://github.com/CesiumGS/cesium/blob/1199e7f5bc1248539b47e5fa818f14ee31c7e2b4/packages/engine/Source/Core/Ellipsoid.js#L496

**Comment by javagl** [comment]
- [x] For some reason, some of the `@see` values at https://github.com/CesiumGS/cesium/blob/0ca6a3e60d8cca6a05aa78d33d5ea7e5e3415be1/packages/engine/Source/Scene/ImageryLayer.js#L530 are not linked in the generated documentation

**Comment by javagl** [comment]
- [ ] Links simply don't work in `@default` tags. For example, https://cesium.com/learn/ion-sdk/ref-doc/ImageryLayer.html#saturation contains `@default {@link ImageryLayer.DEFAULT_SATURATION}`, but the result is not a `@link`.

**Comment by javagl** [comment]
- [ ] The `featureIdLabel` and `instanceFeatureIdLabel` are both defined to be `string` in the JSDoc at https://github.com/CesiumGS/cesium/blob/668c2050e19756a0effbd0ddaa613a350dbf30b3/packages/engine/Source/Scene/Cesium3DTileset.js#L2054 (and below that). But they can actually receive a `number` value, which is magically converted into a `string` internally.

**Comment by javagl** [comment]
- [ ] The [`TilingScheme.prototype.positionToTileXY`](https://github.com/CesiumGS/cesium/blob/668c2050e19756a0effbd0ddaa613a350dbf30b3/packages/engine/Source/Core/TilingScheme.js#L130) and the implementations in [`GeographicTilingScheme`](https://github.com/CesiumGS/cesium/blob/668c2050e19756a0effbd0ddaa613a350dbf30b3/packages/engine/Source/Core/GeographicTilingScheme.js#L204) and [`WebMercatorTilingScheme`](https://github.com/CesiumGS/cesium/blob/668c2050e19756a0effbd0ddaa613a350dbf30b3/packages/engine/Source/Core/WebMercatorTilingScheme.js#L245) boldly claim to return a `Cartesian2`, but they can return `undefined` as well.

**Comment by javagl** [comment]
- [ ] Down to the roots: The [`Rectangle`](https://github.com/CesiumGS/cesium/blob/0ca6a3e60d8cca6a05aa78d33d5ea7e5e3415be1/packages/engine/Source/Core/Rectangle.js#L16) class claims that its coordinates are in radians. And it claims that they are in a certain range. And it claims that `west` is the "westernmost" longitude. None of that is necessarily true. The `TilingScheme.rectangleToNativeRectangle` returns a `Rectangle` that uses degrees, for example. Methods that _receive_ a `Rectangle` usually don't say what unit they expect or which range they accept, or how they handle out-of-range cases. Methods that _return_ a `Rectangle` usually don't say what unit or range they provide. The 'east', 'south', 'west', and 'north' properties don't have a real "meaning" at this point.

Edit after 9 hours of debugging: This does not only affect the _documentation_. Implementations, like that of the `width` getter, _assume_ that the statements from the documentation are true. But they aren't. The results of the computations of these functions are often plainly _wrong_.

**Comment by javagl** [comment]
- [ ] Each and every property of [`Imagery`](https://github.com/CesiumGS/cesium/blob/59741ef773cf29c44f3dcb656469fa2c690f5deb/packages/engine/Source/Scene/Imagery.js#L11) should be documented _extensively_, to make unambiguously clear what the _state space_ of this object is. It can contain farily arbitrary (and sometimes "invalid" or "nonsensical") data, and it is by no means clear which states should be anticipated, and where and how "invalid" states should be handled.

**Comment by javagl** [comment]
- [ ] A generalization of the previous point: Each and every **state** should be documented. This refers to `ImageryState`, [`PrimitiveState`](https://github.com/CesiumGS/cesium/blob/802d8fe61640e95a4930fbb6a05d9f4312743f21/packages/engine/Source/Scene/PrimitiveState.js), and every other state. This should include a clear description of what it _means_ for an object to be in a certain state, as well as extensive descriptions about the conditions, functions, and points in time (why, where, and when) an object goes from one state into another. This might not be necessary if `READY` meant "ready", but here, it **is** necessary.

**Comment by javagl** [comment]
- [ ] The `contentsFetchedPromise` at https://github.com/CesiumGS/cesium/blob/ce6c3e28fc7e550b32a5c67335aa4490d0e84c34/packages/engine/Source/Scene/Multiple3DTileContent.js#L358 does not exist.

**Comment by javagl** [comment]
- [ ] The `unionClippingRegions` at https://github.com/CesiumGS/cesium/blob/027b6352fb8d2cc4282252a6a7fc5be0ff066d31/packages/engine/Source/Scene/ClippingPolygonCollection.js#L259 does not exist

**Comment by javagl** [comment]
- [ ] We could consider updating the inlined sandcastle links from the `index.html?src...` pattern to the `id`-based URLs for the new sandcastle (as mentioned in https://github.com/CesiumGS/cesium/issues/13122#issuecomment-3721472543 ). But that would only be a chore/minor cleanup for now.

**Comment by javagl** [comment]
- [x] I just wondered what `of` is...
  <img width="178" height="82" alt="Image" src="https://github.com/user-attachments/assets/f63b4bc1-de66-48b7-b5ce-c84ade9dff57" />
  Answer: It's a typo (space) at https://github.com/CesiumGS/cesium/blob/8e4375eac0506d2c77ade7d354790c176973e7a8/packages/engine/Source/Scene/Cesium3DTileset.js#L1838

EDIT: This was fixed as part of https://github.com/CesiumGS/cesium/pull/13378

**Comment by javagl** [comment]
- [ ] All `ModelComponents` types are cross-referenced with the `ModelComponents.` prefix, e.g. at https://github.com/CesiumGS/cesium/blob/35fba2628b1a6cc35ae10a9c0f663049f1ebce4a/packages/engine/Source/Scene/ModelComponents.js#L256 . These prefixes don't seem to serve any purpose. They should be removed, and the type exporting should be solved properly (TBD what that means)

**Comment by javagl** [comment]
- [x] The `transform` for the `CubeMapPanorama` is documented to be a `Matrix4`, but apparently, has to be a `Matrix3`, at https://github.com/CesiumGS/cesium/blob/723a1d47752ce1570cc396edbd14edd194dd3443/packages/engine/Source/Scene/CubeMapPanorama.js#L32 

EDIT: I don't understand the purpose of 
`this._transform = options.transform ?? undefined;`
in [this line](https://github.com/CesiumGS/cesium/blob/723a1d47752ce1570cc396edbd14edd194dd3443/packages/engine/Source/Scene/CubeMapPanorama.js#L89). Is this supposed to handle `null`? Probably not. However.

EDIT2: Both have been fixed via https://github.com/CesiumGS/cesium/pull/13339

**Comment by javagl** [comment]
- [ ] https://github.com/CesiumGS/cesium/blob/986264b914b336c761767f367932954d03df0a55/packages/engine/Source/Scene/GaussianSplat3DTileContent.js#L21 should be marked as `@private`/`@ignore`

**Comment by javagl** [comment]
@RickyH22 This is not a "single" issue that can be fixed. It is rather a collection of errors in the documentation that I'm occasionally stumbling over and that I add here just to keep track of them. So it may be difficult to "extract" or "assign" a single issue here. You might consider creating a PR that contains fixes for one or more points that have been mentioned here, but we'll have to see how to organize this in a form that makes sense (e.g. preventing the case where someone opens a different PR that contains _the same_ fixes or ones that overlap with the existing PR...).
