### ISSUE TITLE
Officially support IE 11

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#1616]
While Cesium has not been able to directly support IE in the past, as of IE 11.0.7 (KB2929437), many apps and demos mostly work out of the box.  There are still a few significant problems that have to be addressed before we can claim official support.  Rather than write up a bunch of small issues, I though a single roadmap item would work better, particularly since many of the test failures are probably interrelated.  I'll add to this list as-needed.
- [x] #1731 Something is broken with textures.  This is easiest to see in the Sandcastle label examples, where some letters are missing from words (always the same letters).  The `Renderer/Texture can replace a subset of a texture` test fails as well, so that may be a good place to start.
- [x] #1741 The sun does not render.  This is easy to see in the Models Sandcastle example.  On the plane example, jump to around 2:30 and rotate the camera while close to the plane.  The entire atmosphere will turn black and disappear depending on the camera angle.  This happens whenever the sun is in view.
- [x] #1732 IE constantly spits out this error: WEBGL11095: INVALID_OPERATION: blendColor: Method not currently supported File: RenderState.js, Line: 329, Column: 13.  I'm not sure how hard it is to detect and disable blending.
- [x] #1752 INVALID_OPERATION: disable: Enum SAMPLE_COVERAGE is not currently supported
- [x] #1752 INVALID_OPERATION: enable: Enum DITHER is not currently supported
- [x] #1763 Timeline does not render correctly when going fullscreen from an iframe
- [x] #1776 `Renderer/CubeMap draws with a cube map with premultiplied alpha.`
  `Renderer/Texture renders with premultiplied alpha.`
- [x] INVALID_OPERATION: getUniform (Occurs when Geometry is used: [link](http://localhost:8080/Apps/Sandcastle/gallery/Box.html))
- [ ] #1872 - Timeline trackbar and Animation dial do not stay under the mouse when going fullscreen from an iframe.

DC1 remaining test failures

```
Core/TaskProcessor can transfer array buffer
```
