### ISSUE TITLE
Tween roadmap

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1830]
Common things like mousing over a billboard to animate its size/scale should be robust and trivial, e.g., not like 590a17f9e57d97ca69e2af039c54b79dd68d5179.
- [ ] Use Tween.js only for its easing functions.  This will give us more flexibility with little added complexity.
- [ ] Allow `startValue`/`startObject` and friends to deeply tween their properties, e.g., so they can tween a Cesium `Color` property.  (Related to above).
- [ ] `TweenCollection` `add` functions should take an optional `primitive` property so tweens can check if a primitive was destroyed and remove themselves.
- [ ] Use events instead of callbacks?
- [ ] Ability to create tweens in callbacks, ([#1831 comment](https://github.com/AnalyticalGraphicsInc/cesium/pull/1831#issuecomment-46873220)).
