### ISSUE TITLE
KML Graphics Roadmap

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#2179]
Derived Cesium graphics features for KML (#873).

**Features**
- [x] Vector Data on Terrain: #2172
- [x] Display conditions: #758
- [x] Improved camera flights: #1060 and #1670
- [ ] MSL terrain provider
- [ ] Line width in meters: #1170 (might not need any new graphics code)
- [ ] Support for `gx:drawOrder`?
- [ ] Non-uniform model scale if anyone needs it.
- [x] Handle `-180` to `360` longitude

**Memory usage**
- [x] Unused Polygon Vertices: #1238
- [x] Duplicate polyline vertices?: #898
- [x] Primitive normal compression: #1628
- [x] Billboard vertex compression: #419

**Performance (both loading and rendering)**

Loading Pipeline:
- [x] Default granularity: #2173
- [x] Optimized use of geometry by data sources, e.g., don't compute texture coordinates unless they are needed (perhaps this should be the default).  Use `EllipsoidSurfaceAppearance` for polygons on the globe so we don't have to compute normals.  Etc.
- [x] Profile and analyze geometry pipeline, including (1) the algorithms, and (2) the use of web workers (#1487).  Minimize memory usage throughout the pipeline.
- [x] Investigate new triangulation library: #2074, #1089
- [x] Optimize polygon subdivision
- [x] `PolylinePipeline.wrapLongitude`: #1197
- [x] Giant bounding spheres: #1539
- [ ] Performance ideas from #766
- [ ] Investigate scratch arrays (see #2329)

Rendering:
- [ ] Optimize setting uniforms: #649 and #797 (Uniform buffer objects)
- [ ] Explore different bounding volumes?
- [x] Fog?

**Bugs**
- [x] Transparent billboards: #2130
- [x] Large polygons: #620 (and circles: #998)
- [x] Polygons perpendicular to the earth #3349

**Related Features**
- [ ] Declutter (#1097) and Scale labels based on distance (#1075)
- [ ] Dynamic Buffers: #932

**Comment by mramato** [comment]
[gx:latLonQuad](https://developers.google.com/kml/documentation/kmlreference#gxlatlonquad) is going to require support for trapezoidal texture projection, not sure where that fits in on the G&A pipeline.

[PhotoOverlay](https://developers.google.com/kml/documentation/photos) requires quite a bit of work and probably warrants further investigation with its own issue and roadmap when the time comes.

**Comment by ggetz** [comment]
MSL height conversion was requested in https://community.cesium.com/t/cesium-ion-vs-google-earth-google-photorealistic/27819/9.

**Comment by ggetz** [comment]
MSL lookup is documented in https://github.com/CesiumGS/cesium/issues/11786.

Otherwise all items in this list are covered by their own issue or are listed in https://github.com/CesiumGS/cesium/issues/873. Closing.
