### ISSUE TITLE
Geometry and Appearances

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#766]
_Also see the discussion on the [forum](https://groups.google.com/forum/#!topic/cesium-dev/T0hdTZdb--4)_.

This will introduce a new generic `Primitive` (name TBA) that is higher-level than Renderer, but lower-level than the current primitives.  It is meant for batching of heterogeneous static geometry.  Static means changing the geometry, i.e., the vertex data, is expensive, but changing the `modelMatrix`, is, of course, still cheap.  Dynamic geometry batching is a separate topic, and will require direct, or near direct, access to vertex buffers.

This decouples primitives into geometry and appearance, making it easy to add new geometry types, e.g., boxes, cylinders, etc., and new appearances, e.g., full GLSL shader + render state + [material](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Fabric).  The design is nothing new; it is what is done in pretty much every 3D engine and book out there, and similar to - but more general than - what I did in [Insight3D years ago](http://blogs.agi.com/insight3d/index.php/2008/01/18/introducing-primitives/).

We'll use this to add features for KML, and may rewrite existing primitives - most likely `Polygon` and `EllipsoidPrimitive` - to use it.  The [Geometric Algorithms](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Google-Summer-of-Code-Ideas#wiki-geometricalgorithms) Google Summer of Code proposal is a subset of this effort.

**Example code**

Today we write:

``` javascript
var extent = new Polygon();
extent.configureExtent(
    new Extent(
        Math.toRadians(-180.0),
        Math.toRadians(50.0),
        Math.toRadians(180.0),
        Math.toRadians(90.0)));
primitives.add(extent);
```

In the future, we would write:

``` javascript
var geometry = new ExtentGeometry(
    new Extent(
        Math.toRadians(-180.0),
        Math.toRadians(50.0),
        Math.toRadians(180.0),
        Math.toRadians(90.0)));
var appearance = new SurfaceApperance();

var extent = new Primitive(geometry, appearance);
primitives.add(extent);
```

It's more code.  Don't worry.

(1) it allows for batching:

``` javascript
var geometry = new ExtentGeometry(
    new Extent(
        Math.toRadians(-180.0),
        Math.toRadians(50.0),
        Math.toRadians(180.0),
        Math.toRadians(90.0)));
var otherGeometry = new ExtentGeometry(
    new Extent(
        Math.toRadians(-180.0),
        Math.toRadians(20.0),
        Math.toRadians(180.0),
        Math.toRadians(30.0)));
var apperance = new SurfaceApperance();

var extent = new Primitive([geometry, otherGeometry], appearance);
primitives.add(extent);
```

(2) it is easy to draw new geometry or with new appearances

``` javascript
var geometry = // something read from a file, computed procedurally, taken from user input, etc.
var appearance = new AppearanceIWrote();

var extent = new Primitive(geometry, appearance);
primitives.add(extent);
```

(3) we can write nice (slow) wrappers on top of it:

``` javascript
var extent = new ExtentPrimitive(
    new Extent(
        Math.toRadians(-180.0),
        Math.toRadians(50.0),
        Math.toRadians(180.0),
        Math.toRadians(90.0)));
primitives.add(extent);
```

Now it's less code.  Magic.

The new Primitive allows for individual geometry picking, and high-precision rendering with GPU RTE.  In theory, I think I can make it work for Columbus view too.

**Details**

@bagnell
- [ ] Tech blog post - Web workers
- [ ] Tech blog post - "A WebGL Batching Pipeline."

Primitives
- [ ] Automatically match geometry and appearance `VertexFormat`.
  - In the primitive's geometry pipeline, we can procedurally add normals, binormals, and tangents if the geometry doesn't already have them.  However:
    - This is not as efficient as having the geometry compute them since `Primitive` needs to use generic algorithms.
    - To implement this for when an `Appearance`/`Material` changes (which can change the `VertexFormat`), we would have to keep the geometry in system memory.  Ugh.  This could be an "auto" option I suppose.
    - We can't use generic algorithms to compute texture coordinates; instead, each `Geometry` would need a function to add texture coordinates.
    - At the batching-level of abstraction, requiring the user to match vertex formats may be reasonable so we might not do anything.

Geometries
- [ ] Outline and polyline interop
- [ ] Sector geometry (pie slice)
- [ ] Provide progress update from worker.  Include `onComplete` (for primitives built on geometries too) so, for example, we can destroy a primitive once the new one is ready.
- [ ] Should `WallGeometry` just be an extrusion object for `SimplePolylineGeometry`?
- [ ] Per vertex normals for `PolylineVolumeGeometry` and friends so the polygon can roll, i.e., it is not always oriented north.

Appearances
- [ ] Pass uniforms to appearances
- [ ] What new materials should we add that work well with these new geometries?
- [ ] Ray-casted ellipsoid appearance
- [ ] Ray-casted cylinder appearance

Scripting
- [ ] Scriptable (JSON) geometry
- [ ] Scriptable appearances like materials

Performance
- [x] Use several workers for loading.
- [ ] Store `pickColor` attribute in a separate buffer and have a separate vertex array for the pick pass; this will reduce memory bandwidth and cache pollution for the color pass.
- [ ] Use texture atlas with geometry?
- [ ] Only introduce new vertices for normals for walls and extruded geometries based on the adjacent face angles.
- [ ] Optimize `fitToUnsignedShortIndices` to use tighter bounding spheres per-geometry.

Done

@bagnell
- [x] Add `binormal` and `tangent` attributes to [BoxGeometry](https://github.com/AnalyticalGraphicsInc/cesium/blob/batching/Source/Core/BoxGeometry.js).
- [x] Finish [EllipsoidGeometry](https://github.com/AnalyticalGraphicsInc/cesium/blob/batching/Source/Core/EllipsoidGeometry.js).  It only computes positions right now.
- [x] Replace [ExtentTessellator](https://github.com/AnalyticalGraphicsInc/cesium/blob/batching/Source/Core/ExtentTessellator.js) with a new `ExtentGeometry`.
- [x] Compute all attributes for wall.
- [x] Compute all attributes for polygon.
- [x] Add new `PolygonGeometry` that works with and without holes.  It will not use the full pipeline used in the current Polygon primitive because some of that is in the generic [Primitive](https://github.com/AnalyticalGraphicsInc/cesium/blob/batching/Source/Scene/Primitive.js).
- [x] Add new `CircleGeometry` and `EllipseGeometry`.
- [x] Add new `WallGeometry`.  Meet the needs of KML and Sky.
- [x] Profile to decide if we should change all geometries/tessellators to use typed arrays and `Float64Array`, which will also require some WebGL-related changes.
- [x] Figure out what to do with [HeightmapTessellator](https://github.com/AnalyticalGraphicsInc/cesium/blob/batching/Source/Core/HeightmapTessellator.js).
- [x] Add Columbus view support (notes below)
- [x] How to implement `show` per geometry, i.e., how to change vertex data?  We should be able to change `color` too. (notes below)
- [x] Finish tests
- [x] Fix Sandcastle examples:
  - http://localhost:8080/Apps/Sandcastle/index.html?src=Materials.html
  - http://localhost:8080/Apps/Sandcastle/index.html?src=Custom%20Rendering.html
  - http://localhost:8080/Apps/Sandcastle/index.html?src=Animations.html
  - http://localhost:8080/Apps/Sandcastle/index.html?src=Polygons.html
- [x] Use a dirty list for updating per-instance attributes.
- [x] Extent and ellipse geometries should be able to rotate texture coordinates.
- [x] Optimize bounding sphere created from `GeometryPipeline.combine`.
- [x] Profile geometry pipeline.  What is the optimal order of pipeline stages?
- [x] Investigate moving geometry pipeline to a web worker.
- [x] Back-and-front passes for translucent volumes.  See @pjcozzi.
- [x] Create geometry and appearances for the existing polyline so we can render static polylines efficiently.
- [x] Fix missing triangles in cylinder.  #949 

@hpinkos
- [x] Generic function to compute `binormal` and `tangent` attributes given a geometry with texture coordinates.  See [Computing Tangent Space Basis Vectors for an Arbitrary Mesh](http://www.terathon.com/code/tangent.html).  @tfili has a C++ implementation.
- [x] Generic function to compute `normal` attributes given a geometry with positions.  I can dig up a C++ implementation.
- [x] Add new `ExtrudedExtentGeometry` (with bottom/top) - or make this part of the `ExtentGeometry`.  Meet the needs of KML.
- [x] Add new `ExtrudedPolygonGeometry` (with bottom/top) - or make this part of the `PolygonGeometry`.  Meet the needs of KML.
- [x] `SphereGeometry` based on `EllipsoidGeometry`.
- [x] Ability to extruded `EllipseGeometry` and `CircleGeometry`.
- [x] Add `CylinderGeometry`.  @pjcozzi has C++ code.
- [x] Make `WallGeometry` subsample so it matches the curvature of the ellipsoid.
- [x] Ability to create outlines for `PolygonGeometry`, `ExtentGeometry`, `EllipseGeometry`, `CircleGeometry`, `WallGeometry`, `BoxGeometry`, and `EllipsoidGeometry`.  Go over the design with @pjcozzi beforehand.
- [x] `CorridorGeometry`.  Option to miter or bevel corners.
- [x] `CorridorOutlineGeometry`.
- [x] Generalize corridors and tubes as extruded shapes along a polyline.
- [x] Tubes for aircraft keepout zones.

@pjcozzi
- [x] Add `color` to `VertexFormat`.
- [x] Add `Surface` (procedurally compute normal/binormal/tangent) appearance.
- [x] Customize geometry pipeline in [Primitive](https://github.com/AnalyticalGraphicsInc/cesium/blob/batching/Source/Scene/Primitive.js), e.g., optimize vertex cache.
- [x] Support [OES_element_index_uint](http://www.khronos.org/registry/webgl/extensions/OES_element_index_uint/)
- [x] Support [OES_vertex_array_object](http://www.khronos.org/registry/webgl/extensions/OES_vertex_array_object/)
- [x] Decouple geometry from `modelMatrix`, `color`, and `pickData`, perhaps call it `NodeGeometry` or `Spatial`.  This will allow us to "instance" the geometry, but we need to be careful because many pipeline operations modify the geometry in place.
- [x] Rename `mesh`/`meshes` to `geometry`/`geometries` throughout.
- [x] Finalize `Geometry` format.  In particular: do we need more than one `indexList` and modify `combine` to work without indices.
- [x] Include doc for well-known vertex names
- [x] Finish reference doc
- [x] Match `VertexFormat` and `Appearance`, e.g., add normals if needed.
- [x] `SimplePolyline` geometry and appearance.
- [x] Implement `Polygon` based on geometry and appearance.
- [x] Add `Extent` primitive.
- [x] Add back lighting.
- [x] Two-sided lighting, e.g., for walls.
- [x] Sandcastle example showing different geometry types.

**Comment by ggetz** [comment]
Closing this. Having this roadmap is no longer very useful for tracking issues or enhancements with Geometry and Appearances. Thanks!
